server:
  port: 8086
spring:
  profiles:
    active: local
  config:
    import: "configserver:http://localhost:8088"
  cloud:
    config: # http://localhost:8088/config/local
      name: config
      profile: local
  rabbitmq:
    host: localhost
    port: 5672
    username: glen
    password: glen

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
