server:
  port: 8089
spring:
  profiles:
    active: local
  config:
    import: "configserver:http://localhost:8088"
  cloud:
    config: # http://localhost:8088/config/local
      name: config
      profile: local
management:
  endpoints:
    web:
      exposure:
        include: refresh

