### local static config
GET http://localhost:8089/static
Accept: application/json

### local dynamic config
GET http://localhost:8089/dynamic
Accept: application/json

### refresh scope
POST http://localhost:8089/actuator/refresh
Accept: application/json

### local dynamic config2
GET http://localhost:8086/dynamic
Accept: application/json

### refresh bus
POST http://localhost:8089/actuator/busrefresh
Accept: application/json